print("hdello world")

slicing
syntax [start argumenr:end arugument:step]

example :
  
lang="python"
print(lang[0:-1]) 
print("lang"[0:2]) 
print("python"[:2]) 
print("ACCOUNT"[::]) 

a=input("enter the name")
print(a[::-1])

print("harshit"[::-2]) 
print("harshit"[::-3])
print("harshit"[5::-1])
print("harshit"[1::-1])

print("python"[0:6])
print("python"[0:6:2])

print("shruti"[0:6:3])

print("mother"[1:5:3])

print("Vandana"[3:7:3])
